alias A='vi ~/.bash_aliases; source ~/.bash_aliases'
alias Developers='sudo mount -t cifs -o username=rroble //S/Developers /media/S/Developers/'
alias Development='sudo mount -t cifs -o username=rroble //S/Development /media/S/Development/'
alias vims='sudo vim'
alias pingg='ping google.com'
alias I='sudo apt install'
alias C='vim ~/.config/i3/config'
alias Ego='cd ~/exercism/go'
alias R='rifle'
alias Shutdown='sudo shutdown now'
alias Reboot='sudo reboot'
alias E='exercism'
alias Src='cd ~/go/src'
alias T='cd ~/go/src/github.com/tiqqe'
alias Thm='cd ~/go/src/github.com/tiqqe/allegro-hm-credit-request'
alias gits='git submodule update --init --recursive'
alias where='grep -r'
