alias A='vi ~/.bash_aliases; source ~/.bash_aliases'
alias Developers='sudo mount -t cifs -o username=rroble //S/Developers /media/S/Developers/'
alias Development='sudo mount -t cifs -o username=rroble //S/Development /media/S/Development/'
alias vims='sudo vim'
alias pingg='ping google.com'
alias apts='sudo apt install'
alias C='vim ~/.config/i3/config'
